[package]
name = "actix_web_metrics_mw"
version = "0.0.1"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"
description = "Actix middleware library for metrics"
homepage = "https://github.com/Igosuki/actix_web_metrics_mw"
repository = "https://github.com/Igosuki/actix_web_metrics_mw"
documentation = "https://docs.rs/actix_web_metrics_mw"

[dependencies]
actix-web = "1.0.5"
futures = "0.1.28"
actix-service = "0.4.1"
metrics = "0.11.1"
metrics-core = "0.5.1"
metrics-runtime = "0.1.0"
log = "0.4.8"

#statsd = "^0.9.0"
cadence = "0.18.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

