version: "3"
services:
  # Grafana on port 3003, login = root / root
  # Data-Source -> add InfluxDB
  # doc is available at https://hub.docker.com/r/samuelebistoletti/docker-statsd-influxdb-grafana/
  metrics:
    image: samuelebistoletti/docker-statsd-influxdb-grafana:latest
    restart: always
    ports:
      - 3003:3003
      - 3004:8888
      - 8086:8086
      - 8125:8125/udp


